export interface IGameError {
  code: string;
  message: string;
}

export const AD_LOAD_FAILED = 'AD_LOAD_FAILED';
export const EVENT_CONFIG_NOT_FOUND = 'EVENT_CONFIG_NOT_FOUND';
export const EVENT_REWARD_ALREADY_CLAIMED = 'EVENT_REWARD_ALREADY_CLAIMED';
export const EVENT_REWARD_EXPIRED = 'EVENT_REWARD_EXPIRED';
export const EVENT_REWARD_INELIGIBLE = 'EVENT_REWARD_INELIGIBLE';
export const IAP_PURCHASE_FAILED = 'IAP_PURCHASE_FAILED';
export const MONETIZATION_UNAVAILABLE = 'MONETIZATION_UNAVAILABLE';
export const SAVE_LOAD_FAILED = 'SAVE_LOAD_FAILED';
export const STAGE_CONFIG_NOT_FOUND = 'STAGE_CONFIG_NOT_FOUND';
export const STAGE_CONFIG_INVALID = 'STAGE_CONFIG_INVALID';
