export const AD_LOAD_FAILED = 'AD_LOAD_FAILED';
export const SAVE_LOAD_FAILED = 'SAVE_LOAD_FAILED';
export const STAGE_CONFIG_NOT_FOUND = 'STAGE_CONFIG_NOT_FOUND';
export const STAGE_CONFIG_INVALID = 'STAGE_CONFIG_INVALID';
